### ISSUE TITLE
Install latex

### ISSUE THREAD

**Issue by tvvocold** [purpleidea/pdfdoc#3]
hi @purpleidea ,

Cool project!
And here is what my step:

```
$ rhc create-app pdfdoc python-3.3 --from-code https://github.com/purpleidea/pdfdoc
$ rhc ssh pdfdoc 
$ cd app-root/repo && mv static ../data && mv pandoc ../data/static
$ cd wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz && tar -xf install-tl-unx.tar.gz
$ ./ti-install 
$ Enter command: D >Enter command: 1 >
   New value for TEXDIR [/usr/local/texlive/2014]:$OPENSHIFT_DATA_DIR/latex/
$ Enter command: I
```

But then why i got [this](https://gist.githubusercontent.com/tvvocold/ed994927e9f714a0c6fb/raw/9bcc3bd5a42d879e0377af9bce33a6e8a0852690/gistfile1.txt) and how to fix?

Thanks,
Ray

**Comment by tvvocold** [comment]
Oops, looks like i should type `../latex` in `New value for TEXDIR`.
Sry to bother u.

**Comment by tvvocold** [comment]
But why after i did a medium size install and gear run out of quota?
Then why i run a basic install and got Error processing URL :(

**Comment by purpleidea** [comment]
@tvvocold if you don't have enough disk, you'll need to do a small latex install and/or use a bigger gear.
